### PR TITLE
Add a feature for the love2D workshop

### PR DESCRIPTION
**Pull request by moosichu**
Also adds the framework for further workshops

Screenshot of the feature change

### CODE REVIEW

**Comment by moosichu** [comment]
DO NOT MERGE UNTIL THIS EVENT IS LIVE! https://www.facebook.com/events/128537371191407/

**Comment by jaredkhan** [comment]
From screenshot, feature should have `textShade: .light`

**Comment by moosichu** [comment]
@jaredkhan It does, sorry, the screenshot is missing that one last minute changed I made!

**Comment by Pinpickle** [comment]
I think this is an example of where our feature mechanism breaks down. Ideally we'd have the Game Gig feature up for getting tickets, not leading up to the event itself.

We could hack around that for the time being by inserting it multiple times?

**Comment by jaredkhan** [comment]
@moosichu does this have an urgey for mergey?

**Comment by moosichu** [comment]
@jaredkhan It would be nice if we could mergey

**Comment by moosichu** [comment]
Once we merge this, we need to create an issue to add event banners for the Game Gig and the Unity workshop.

**Pull request merged**
