### PR TITLE
Style the individual workshop page

### LINKED ISSUE #159: Design and implement a page to view specific workshops
## What the enhancement is
A page to view the details of a specific workshop. It should show any useful details from the workshop model e.g. description, prerequisites, set-up instructions

At this point it needn't show upcoming dates, this is a separate issue (see #161)

### PR DESCRIPTION
**Pull request by jaredkhan**
Fixes #159

Notable missing:
- Good handling of code snippets
- Embedding of any content (slides or recording), might not be particularly convenient to do this anyway

Now
screen shot 2018-01-13 at 23 48 27
screen shot 2018-01-13 at 23 48 38
screen shot 2018-01-13 at 23 48 50

### CODE REVIEW

**Comment by Pinpickle** [comment]
Why wouldn't it be convenient to embed recordings? I can understand why slides would be clunky.

Confirming: this isn't using actual data yet, is it?

**Comment by jaredkhan** [comment]
@Pinpickle I’m thinking it’s probably going to be more convenient for users to open the recording in a new tab so they can scroll the content while listening to the recording

**Comment by Pinpickle** [comment]
@jaredkhan that's a reasonable thought. In my experience people have been "either or" with videos vs written content. Either the video has worked for them or the written content has (or they're in a particular mood for on or the other).

Let's go with the least-effort path for now, though (a link)

**Comment by jaredkhan** [comment]
@Pinpickle True but I don’t think we should necessarily encourage that because I think it’ll make people less likely to engage in the exercises. A discussion for another time

**Pull request merged**
