### PR TITLE
Event Feature text overlay - background added for contrast

### LINKED ISSUE #239: Replace "light" and "dark" text over features with a dark box with light text
Currently, we have text on top of our feature on the home page to display the date. To accommodate for different coloured images, that text can be either "dark" or "light". While a nice design feature, this is a pain to work with. The text should be background-agnostic, eg a dark box and light text.

Here is the code where we create the text on top:

https://github.com/hackersatcambridge/hac-website/blob/master/Sources/HaCWebsiteLib/Views/LandingPage/EventFeature.swift#L29-L44

### PR DESCRIPTION
**Pull request by eliotlim**
+ EventFeature.styl: Added a background and rounded border for the overlay text
- EventFeature.swift: Modified `TextShade` enum to resolve as `EventFeature--text-light`.

Fixes #239.

Screenshots (for frontend changes only):
Before

After

### CODE REVIEW

**Comment by eliotlim** [comment]
Here's a screenshot of the result when a lighter background is used!

Lighter BG Overlay Preview

**Comment by eliotlim** [comment]
I'm inclined to agree. Would it be okay if I removed `TextShade`, or is
there a plan to use it for another visual feature?

**Comment by CharlieCrisp** [comment]
@eliotlim I think it's fine but @jaredkhan or @Pinpickle can you confirm?

**Comment by jaredkhan** [comment]
@eliotlim Yup, `TextShade` should go

**Comment by eliotlim** [comment]
I've removed the `TextShade` enum and updated the relevant LandingFeatures.

**Pull request merged**
