### PR TITLE
Landing copy

### PR DESCRIPTION
**Pull request by jaredkhan**
Uses the Markdown node introduced in #127 to simplify the Landing copy

### CODE REVIEW

**Comment by moosichu** [comment]
Also adds a link to the demonstrators group?

**Comment by jaredkhan** [comment]
@moosichu Yep, that link was supposed to be there before. Fixes a couple other typos too.

**Comment by moosichu** [comment]
Also, now you can see why I love the new swift 4 multiline strings

**Comment by CharlieCrisp** [comment]
This is really nice!

**Pull request merged**
