### PR TITLE
Add pizzazz to About headers

### PR DESCRIPTION
**Pull request by jaredkhan**
Adds a little glam to the landing page headlines

Screenshots (for frontend changes only):

Previously
screen shot 2017-11-10 at 22 37 13

Now
screen shot 2017-11-10 at 22 37 25

### CODE REVIEW

**Comment by CharlieCrisp** [comment]
I like it! Is this going to be affected by the changes you were sketching out the other day @jaredkhan?

**Comment by jaredkhan** [comment]
@CharlieCrisp Maybe but I think these headers might stick around. Either way, I think this is nicer in the meantime 😊

**Comment by moosichu** [comment]
I need to look at in the context of the actual page. I really like the font, but this also lowers the information density of the page. (The headers taking up more space now). However, I do like it a lot. @Pinpickle Any comments?

**Comment by jaredkhan** [comment]
@moosichu You're right but I don't think information density was ever particularly a goal

**Comment by Pinpickle** [comment]
@moosichu we say information density like more is better but I don't think that's necessarily true.

However, I think in the context of smaller screens (like this screenshot), the headings are pretty overpowering. @jaredkhan what do you think of a media query to make them a touch smaller on smaller screens?

Something else that might help here is giving the headings a little more room to breath, ie some extra margin below them.

**Comment by jaredkhan** [comment]
Yeah we could make them smaller on smaller screens. I think perhaps the column breakpoint is too small as well.

**Comment by jaredkhan** [comment]
@Pinpickle @moosichu How's that?

**Comment by Pinpickle** [comment]
@jaredkhan can we get some screenies?

**Comment by jaredkhan** [comment]
I'll do you one better. Have 10 screenies per second
http://recordit.co/TXgxbGwdYT

**Pull request merged**
